### PR TITLE
Fixes to tutorial and code for deployment to Google Container Engine

### PR DESCRIPTION
**Pull request by duebbert**
This should work now if following all steps from a completely fresh project.

### CODE REVIEW

**Comment by pconerly** [comment]
I disagree with removing `frontend.yaml` and `postgres.yaml`, I think that having them availible to simply be edited and browsed is very instructive, especially for people who aren't going to complete the tutorial.  But just my 2 cents, as someone who is halfway through the tutorial.

**Comment by duebbert** [comment]
You have both files available as templates which are much better to use because they have comments what variables need to be changed.

**Comment by waprin** [comment]
@duebbert wow sorry I totally missed this PR, feel free to ping me again next time. Thanks for the changes, looks great. I am going to take another pass at getting this all updated this week.

**Comment by duebbert** [comment]
@waprin No problem, Bill. It was a lot of changes, so I thought you didn't want to tackle it... would be great if you updated this with the new features (like PetSet?). I'd be happy to run through it to test that all works for noobs like me (still not doing that much with Kubernetes).

**Pull request merged**
